spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_oauth?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: '00294572'
server:
  port: 8282



jwt:
  key: '926D96C90030DD58429D2751AC1BDBBC'
  expiration: 864000000
